# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MaskImageDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MaskImageDemo
  pod "BSImagePicker", "~> 3.1"
  pod 'lottie-ios'

end
